# Generated by Django 4.2.7 on 2023-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidvpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
