# Generated by Django 4.2.7 on 2023-11-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidvpt', '0004_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
